theme: minima
title: my awesome blog 
author: butgit
email: schooler@daum.net
description: > # this means to ignore newlines until "baseurl:"
  this is my awesome blog. this is gonna be full of useful codes. this will help with my work and life. 
  
# social links
twitter_username: your-twitter-handle
github_username:  butgit

show_excerpts: true # set to false to remove excerpts on the homepage
